hw3: main.o linearProbingHash.o doubleHash.o universalHash.o
	g++ main.o linearProbingHash.o doubleHash.o universalHash.o -o hw3
main.o: main.cpp
	g++ -c -std=c++11 main.cpp
linearProbingHash.o: linearProbingHash.cpp
	g++ -c -std=c++11 linearProbingHash.cpp
doubleHash.o: doubleHash.cpp
	g++ -c -std=c++11 doubleHash.cpp
universalHash.o: universalHash.cpp
	g++ -c -std=c++11 universalHash.cpp
